In [3]:
import pandas as pd 


data3 = pd.read_csv("var_exp_1_not.csv")
data4 = pd.read_csv("var_exp_2_1_not.csv")
data1 = pd.read_csv("var_exp_1.csv")
data2 = pd.read_csv("var_exp_2_1.csv")

model_name_conversion = {
    'openai--gpt-4o-mini': 'GPT-4o-mini',
    'openai--gpt-4o': 'GPT-4o',
    'llama3_1_instruct--70b': 'Llama-3.1-70B-Instruct',
    'llama3_1--8b': 'Llama-3.1-8B',
    'gemma2--9b': 'Gemma-9B',
    'qwen2--7b': 'Qwen-7B',
    'exaone--8b': 'ExaOne-8B',
    'type' : 'MV'
}

data1.columns = data1.columns.map(model_name_conversion)
data2.columns = data2.columns.map(model_name_conversion)
data3.columns = data3.columns.map(model_name_conversion)
data4.columns = data4.columns.map(model_name_conversion)
data1['Setting'] = 'D (+)'
data2['Setting'] = 'C (+)'
data3['Setting'] = 'D (-)'
data4['Setting'] = 'C (-)'

# make sure setting comes first
data1 = data1[['Setting'] + [col for col in data1.columns if col != 'Setting']]
data2 = data2[['Setting'] + [col for col in data2.columns if col != 'Setting']]
data3 = data3[['Setting'] + [col for col in data3.columns if col != 'Setting']]
data4 = data4[['Setting'] + [col for col in data4.columns if col != 'Setting']]

# Drop Exaone-8B column for all dataframes
data1 = data1.drop(columns=['ExaOne-8B'])
data2 = data2.drop(columns=['ExaOne-8B'])
data3 = data3.drop(columns=['ExaOne-8B'])
data4 = data4.drop(columns=['ExaOne-8B'])

In [4]:
# convert into markdown table
data1

,Setting,MV,GPT-4o,GPT-4o-mini,Llama-3.1-70B-Instruct,Llama-3.1-8B,Gemma-9B,Qwen-7B
0,D (+),none,0.05,0.17,0.06,0.02,0.09,0.24
1,D (+),strong,0.01,0.01,0.06,0.00,0.00,0.03
2,D (+),weak,0.02,0.25,0.04,0.01,0.04,0.23

In [5]:
data2

,Setting,MV,GPT-4o,GPT-4o-mini,Llama-3.1-70B-Instruct,Llama-3.1-8B,Gemma-9B,Qwen-7B
0,C (+),none,0.02,0.03,0.01,0.17,0.10,0.14
1,C (+),strong,0.02,0.01,0.12,0.01,0.04,0.04
2,C (+),weak,0.03,0.17,0.00,0.21,0.22,0.13

In [6]:
data3

,Setting,MV,GPT-4o,GPT-4o-mini,Llama-3.1-70B-Instruct,Llama-3.1-8B,Gemma-9B,Qwen-7B
0,D (-),none,0.02,0.09,0.07,0.01,0.25,0.15
1,D (-),strong,0.10,0.12,0.21,0.00,0.12,0.15
2,D (-),weak,0.03,0.25,0.17,0.02,0.23,0.23

In [7]:
data4

,Setting,MV,GPT-4o,GPT-4o-mini,Llama-3.1-70B-Instruct,Llama-3.1-8B,Gemma-9B,Qwen-7B
0,C (-),none,0.01,0.03,0.01,0.18,0.03,0.11
1,C (-),strong,0.02,0.01,0.11,0.00,0.11,0.03
2,C (-),weak,0.03,0.13,0.03,0.15,0.06,0.16

In [6]:
print(data1.to_markdown())
print(data2.to_markdown())
print(data3.to_markdown())
print(data4.to_markdown())

|    | Setting   | MV     |   GPT-4o-mini |   Llama-3.1-70B-Instruct |   Llama-3.1-8B |   Gemma-9B |   Qwen-7B |
|---:|:----------|:-------|--------------:|-------------------------:|---------------:|-----------:|----------:|
|  0 | D (+)     | none   |          0.18 |                     0.06 |           0.02 |       0.09 |      0.24 |
|  1 | D (+)     | strong |          0.01 |                     0.06 |           0    |       0    |      0.03 |
|  2 | D (+)     | weak   |          0.25 |                     0.04 |           0.01 |       0.04 |      0.23 |
|    | Setting   | MV     |   GPT-4o-mini |   Llama-3.1-70B-Instruct |   Llama-3.1-8B |   Gemma-9B |   Qwen-7B |
|---:|:----------|:-------|--------------:|-------------------------:|---------------:|-----------:|----------:|
|  0 | C (+)     | none   |          0.01 |                     0.01 |           0.01 |       0.04 |      0.04 |
|  1 | C (+)     | strong |          0.04 |                     0.12 |           0.25 |       0.1  |      0.1  |
|  2 | C (+)     | weak   |          0.02 |                     0    |           0    |       0.13 |      0.02 |
|    | Setting   | MV     |   GPT-4o-mini |   Llama-3.1-70B-Instruct |   Llama-3.1-8B |   Gemma-9B |   Qwen-7B |
|---:|:----------|:-------|--------------:|-------------------------:|---------------:|-----------:|----------:|
|  0 | D (-)     | none   |          0.11 |                     0.07 |           0.01 |       0.25 |      0.15 |
|  1 | D (-)     | strong |          0.1  |                     0.21 |           0    |       0.12 |      0.15 |
|  2 | D (-)     | weak   |          0.25 |                     0.17 |           0.02 |       0.23 |      0.23 |
|    | Setting   | MV     |   GPT-4o-mini |   Llama-3.1-70B-Instruct |   Llama-3.1-8B |   Gemma-9B |   Qwen-7B |
|---:|:----------|:-------|--------------:|-------------------------:|---------------:|-----------:|----------:|
|  0 | C (-)     | none   |          0.01 |                     0.01 |           0    |       0.01 |      0.02 |
|  1 | C (-)     | strong |          0.03 |                     0.11 |           0.24 |       0.21 |      0.07 |
|  2 | C (-)     | weak   |          0.01 |                     0.03 |           0    |       0    |      0.02 |